In [68]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')
import cv2

In [87]:
import numpy as np
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment

def emd_2d(dist1, dist2):
    # Calculate pairwise distances between points in the two distributions
    distances = cdist(dist1, dist2)

    # Solve the linear sum assignment problem to find the optimal point-to-point assignments
    row_indices, col_indices = linear_sum_assignment(distances) 

    # Calculate the Earth Mover's Distance
    emd = np.sum(distances[row_indices, col_indices])
    
    print(distances)
    print(distances[row_indices, col_indices])
    print(dist1.shape, dist2.shape)
    return emd

# Example 2D distributions as numpy arrays
distribution1 = np.array([[1, 2], [3, 4], [5, 7]])
distribution2 = np.array([[2, 2], [4, 4], [8, 5]])

emd_distance = emd_2d(distribution1, distribution2)
print("Earth Mover's Distance:", emd_distance)


[[1.         3.60555128 7.61577311]
 [2.23606798 1.         5.09901951]
 [5.83095189 3.16227766 3.60555128]]
[1.         1.         3.60555128]
(3, 2) (3, 2)
Earth Mover's Distance: 5.60555127546399


In [63]:
from scipy.stats import wasserstein_distance
wasserstein_distance([[0, 1, 2],[0, 1, 2]], [[6,7, 8],[6,7, 8]])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [44]:
#reference array:
H, edges = np.histogramdd(ref[0], bins = 80)
a = np.zeros((len(H), 2))
for i, x in enumerate(H):
    a[i][0] = x
    a[i][1] = edges[0][i]


# #measured array:

H, edges = np.histogramdd(data[0], bins = 80)
aa = np.zeros((len(H), 2))
for ii, xx in enumerate(H):
    aa[ii][0] = xx
    aa[i][1] = edges[0][ii]


In [73]:
# ref array
# cv_array_ref = cv2.cv.fromarray(a)
cv_array_ref = a
a32 = a
# a32 = cv.CreateMat(cv_array_ref.rows, cv_array_ref.cols,cv.CV_32FC1)
# cv2.cv.Convert(cv_array_ref, a32)
#measured array:
# cv_array_meas = cv2.cv.fromarray(aa)
cv_array_meas = aa
a322 = aa
# a322 = cv.CreateMat(cv_array_meas.rows, cv_array_meas.cols, cv2.cv.CV_32FC1)
# cv2.cv.Convert(cv_array_meas, a322)

cv.EMD(a32, a322,distType=1)


# vis2 = cv.CreateMat(h, w, cv.CV_32FC3)
# vis0 = cv.fromarray(vis)

error: OpenCV(4.8.0) /io/opencv/modules/imgproc/src/emd.cpp:187: error: (-210:Unsupported format or combination of formats) The signatures must be 32fC1 in function 'cvCalcEMD2'
